# Generated by Django 5.2.7 on 2025-11-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_review_owner"),
        ("users", "0004_alter_profile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["created"]},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("owner", "project")},
        ),
    ]
