# Generated by Django 5.2.7 on 2025-11-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_options_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-vote_ratio", "-vote_total", "title"]},
        ),
    ]
